# Generated by Django 5.0 on 2023-12-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prova', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prova',
            name='body',
        ),
        migrations.RemoveField(
            model_name='prova',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='prova',
            name='created',
        ),
        migrations.RemoveField(
            model_name='prova',
            name='updated',
        ),
        migrations.AddField(
            model_name='prova',
            name='UC',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prova',
            name='duracao',
            field=models.CharField(default='90 minutos', max_length=20),
        ),
        migrations.AddField(
            model_name='prova',
            name='exam_identifier',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prova',
            name='exam_type',
            field=models.CharField(default='enunciado', max_length=50),
        ),
        migrations.AddField(
            model_name='prova',
            name='questions',
            field=models.JSONField(null=True),
        ),
    ]
